export const colorMap: Record<string, string> = {
  greenButton: "#72bf78",
  grayButton: "#B6B6B6",
  input: "#e0dbdb",
  inputText: "#706c6c",
  blackText: "#4E4949",
  whiteText: "#fff",
  grayText: "#7B846F",
  embed: "#E8F1EC",
  embed2: "#B1C3B9"
};

export const translate: Record<string, Record<string, string>> = {
  ua: {
    "Sign up": "Зареєструватися",
    "Log in": "Увійти",
    "Privacy Policy": "Політикою конфіденційності",
    "I agree to the": "Я погоджуюся з ",
    "Continue with Google": "Продовжити через Google",
    "Continue with Apple": "Продовжити через Apple",
    or: "або",
    "Create account": "Створити акаунт",
    "What's your email?": "Ваша електронна адреса?",
    "You’ll need to confirm this email later":
      "Вам потрібно буде підтвердити цю електронну адресу пізніше",
    "Create a password": "Створіть пароль",
    "Enter your password": "Введіть ваш пароль",
    "Use at least 8 characters": "Використовуйте щонайменше 8 символів",
    "Repeat the password": "Повторіть пароль",
    "Repeat your password": "Повторіть ваш пароль",
    Next: "Далі",
    "What's your name?": "Як вас звати?",
    "Name": "Ім'я",
    "This appears on your profile": "Це буде відображено у вашому профілі",
    "Hello": "Привіт",
    "Start" : "Розпочати",
    "Create a team": "Створити команду",
    "What's the ID of your drone": "Який ID головного дрона",
    "Enter the drone ID": "Введіть ID дрону",
    "What's the ID of your shepherd": "Який ID дрона пастуха",
    "Add shepherd": "Додати пастуха",
    "Create grazing": "Створити випас",
    "Choose the type of animal": "Оберіть тип тварини",
    "Enter the quantity": "Введіть кількість",
    "Choose the duration of the walk": "Оберіть тривалість прогулянки",
    "Choose a location": "Оберіть місце",
    "1 Hour": "1 Година",
    "2 Hours": "2 Години",
    "3 Hours": "3 Години",
    "4 Hours": "4 Години",
    "5 Hours": "5 Годин",
    "6 Hours": "6 Годин",
    "Loading...": "Завантаження...",
    Grazing: "Випас",
    "Grazing Overview": "Огляд випасу",
    "Drone Password": "Пароль дрона",
    "Shepherd drone IDs": "ID дронів пастухів",
    "Not Available": "Немає в наявності",
    "Animal": "Тварина",
    "Quantity": "Кількість",
    "Duration": "Тривалість",
    "My location": "Моя локація",
    "Let's go": "Поїхали",
    "Add grazing": "Додати випас",
    Back: "Назад",
    "Team Details": "Деталі команди",
    "Grazing Details": "Деталі випасу",
    "Back to Team Creation": "Назад до створення команди",
    "Choose an animal": "Виберіть тварину",
    "Choose a duration": "Виберіть тривалість",
    "Complete": "Завершити",
    "Stream": "Трансляція",
    "Can't log in. User data not found.": "Неможливо увійти. Дані користувача не знайдено.",
    "An error occurred. Please try again.": "Виникла помилка. Спробуйте ще раз.",
    "Cows 🐄": "Корови 🐄",
    "Goats 🐐": "Кози 🐐",
    "Ducks 🦆": "Качки 🦆",
    "Horses 🐎": "Коні 🐎",
    "Sheep 🐑": "Вівці 🐑",
    "Donkeys 🐴": "Осли 🐴",
    "No grazing data": "Немає даних про випас",
    "Account": "Акаунт",
    "Main drone ID": "ID головного дрона",
    "Enter the main drone ID": "Ведіть ID головного дрона",
    "Drone ID": "ID дрона",
    "Shepherd drone ID": "ID дрона пастуха",
    "Enter the shepherd drone ID": "Введіть ID дрона пастуха",
    "Drone team": "Команда дронів"
  },
  en: {
    "Sign up": "Sign up",
    "Log in": "Log in",
    "Privacy Policy": "Privacy Policy",
    "I agree to the": "I agree to the",
    "Continue with Google": "Continue with Google",
    "Continue with Apple": "Continue with Apple",
    or: "or",
    "Create account": "Create account",
    "What's your email?": "What's your email?",
    "You’ll need to confirm this email later": "You’ll need to confirm this email later",
    "Create a password": "Create a password",
    "Enter your password": "Enter your password",
    "Use at least 8 characters": "Use at least 8 characters",
    "Repeat the password": "Repeat the password",
    "Repeat your password": "Repeat your password",
    Next: "Next",
    "What's your name?": "What's your name?",
    "Name": "Name",
    "This appears on your profile": "This appears on your profile",
    "Hello": "Hello",
    "Start": "Start",
    "Create a team": "Create a team",
    "What is your drone's password?": "What is your drone's password?",
    "Enter the drone ID": "Enter the drone ID",
    "What's the ID of your shepherd": "What's the ID of your shepherd",
    "Add shepherd": "Add shepherd",
    "Create grazing": "Create grazing",
    "Choose the type of animal": "Choose the type of animal",
    "Enter the quantity": "Enter the quantity",
    "Choose the duration of the walk": "Choose the duration of the walk",
    "Choose a location": "Choose a location",
    "Cows": "Cows",
    "Goats": "Goats",
    "Dogs": "Dogs",
    "Horses": "Horses",
    "Sheep": "Sheep",
    "Donkeys": "Donkeys",
    "1 Hour": "1 Hour",
    "2 Hours": "2 Hours",
    "3 Hours": "3 Hours",
    "4 Hours": "4 Hours",
    "5 Hours": "5 Hours",
    "6 Hours": "6 Hours",
    "Loading...": "Loading...",
    Grazing: "Grazing",
    "Grazing Overview": "Grazing Overview",
    "Drone Password": "Drone Password",
    "Shepherd drone IDs": "Shepherd drone IDs",
    "Not Available": "Not Available",
    "Animal": "Animal",
    "Quantity": "Quantity",
    "Duration": "Duration",
    "My location": "My location",
    "Let's go": "Let's go",
    "Add grazing": "Add grazing",
    Back: "Back",
    "Team Details": "Team Details",
    "Grazing Details": "Grazing Details",
    "Back to Team Creation": "Back to Team Creation",
    "Choose an animal": "Choose an animal",
    "Choose a duration": "Choose a duration",
    "Complete": "Complete",
    "Stream": "Stream",
    "Can't log in. User data not found.": "Can't log in. User data not found.",
    "An error occurred. Please try again.": "An error occurred. Please try again.",
    "Cows 🐄": "Корови 🐄",
    "Goats 🐐": "Кози 🐐",
    "Ducks": "Качки 🦆",
    "Horses 🐎": "Коні 🐎",
    "Sheep 🐑": "Вівці 🐑",
    "Donkeys 🐴": "Осли 🐴",
    "No grazing data": "No grazing data",
    "Account": "Account",
    "Main drone ID": "Main drone ID",
    "Enter the main drone ID": "Enter the main drone ID",
    "Drone ID": "Drone ID",
    "Shepherd drone ID": "Shepherd drone ID",
    "Enter the shepherd drone ID": "Enter the shepherd drone ID",
    "Drone team": "Drone team",
  },
};


export const height = 50;
export const height2 = 42;